# -*- coding: utf-8 -*-
"""SalaryPredictor.ipynb

Automatically generated by Colaboratory.

"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

#Importing dataset
dataset = pd.read_csv("/content/drive/My Drive/Colab Notebooks/SimpleLinearRegression/SalaryPredictor/Salary_Data.csv")

#Extracting Features and Labels
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting train and test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#Training the Model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#Predicting the test set results
y_pred = regressor.predict(X_test)

#Plotting training set results
plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.title('Salary vs Years of Experience (Training Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')

#Plotting test set results
plt.scatter(X_test, y_test, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.title('Salary vs Years of Experience (Test Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')